# Generated by Django 5.1.3 on 2024-12-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htask', models.CharField(max_length=50)),
                ('hdescription', models.CharField(max_length=1024)),
            ],
        ),
    ]
